update rust.yml

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -47,19 +47,26 @@ jobs:
       env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: |
-        # Install Homebrew
-        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
-        
-        # Add Homebrew to PATH
-        echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
-
-        # Clone the Homebrew tap repository
-        git clone https://github.com/raphaelmansuy/homebrew-tap.git
-        cd homebrew-tap
-
-        # Update the Homebrew formula
-        brew bump-formula-pr --version="${{ github.ref }}" --url="https://github.com/raphaelmansuy/hiramu-cli/archive/${{ github.ref }}.tar.gz" hiramu-cli
-
-        # Push the changes to the Homebrew tap repository
-        git push origin master
+            # Install Homebrew
+            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+            
+            # Check if Homebrew is installed
+            if ! command -v brew &> /dev/null
+            then
+                echo "Homebrew could not be installed"
+                exit 1
+            fi
+          
+            # Add Homebrew to PATH
+            echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
+          
+            # Clone the Homebrew tap repository
+            git clone https://github.com/raphaelmansuy/homebrew-tap.git
+            cd homebrew-tap
+          
+            # Update the Homebrew formula
+            brew bump-formula-pr --version="${{ github.ref }}" --url="https://github.com/raphaelmansuy/hiramu-cli/archive/${{ github.ref }}.tar.gz" hiramu-cli
+          
+            # Push the changes to the Homebrew tap repository
+            git push origin master
 
